### ISSUE TITLE
Compatibilité Symfony 2.6

### ISSUE THREAD

**Issue by Naelyth** [vincentchalamon/VinceTypeBundle#3]
Pour la compatibilité de Symfony 2.6, il manque au fichier form_div_layout.html.twig les blocs suivants :
 * _my_bundle_vehiclebundle_vehicle_submit_stylesheet
 * submit_stylesheet-
 * button_stylesheet
 * _my_bundle_vehiclebundle_vehicle_submit_javascript
 * submit_javascript
 * button_javascript
Ainsi qu'une mise à jour du composer.json qui permettra de chercher du côté de Symfony 2.6.

Serait-ce possible à mettre en place ?

**Comment by vincentchalamon** [comment]
Il tient à vous de créer ces blocs dans votre fichier `form_div_layout.html.twig`, et de charger celui-ci dans votre projet en complément à celui fourni par défaut dans ce bundle

**Comment by Naelyth** [comment]
D'accord, merci pour l'info.

**Comment by vincentchalamon** [comment]
PR de @samuel-queniart mergée
